name: Deploy pr preview
on: 
  - pull_request
jobs:
  deploy-pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $GITHUB_CONTEXT
      - name: Prepare runner with ssh keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan $DOKKU_HOST >> ~/.ssh/known_hosts
      - name: Create dokku app for pr branch if dosent already exist using dokku apps:create
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          echo The PR was raised by: ${{ github.event.pull_request.user.login }}
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          echo Creating dokku app ${{ github.event.pull_request.user.login }}-${{ github.head_ref }}
          ssh dokku@$DOKKU_HOST -C "apps:create ${{ github.event.pull_request.user.login }}-${{ github.head_ref }}" | true
          echo The url will be ${{ github.event.pull_request.user.login }}-${{ github.head_ref }}.dickyindra.com
          ssh dokku@$DOKKU_HOST -C "git:initialize ${{ github.event.pull_request.user.login }}-${{ github.head_ref }}"
          ssh dokku@$DOKKU_HOST -C "git:set ${{ github.event.pull_request.user.login }}-${{ github.head_ref }} deploy-branch ${{ github.head_ref }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy branch ${{ github.head_ref }} to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          app-name: ${{ github.event.pull_request.user.login }}-${{ github.head_ref }}
          git-push-flags: '--force'
          remote-branch: ${{ github.head_ref }}
      - name: Click to see your PR web address
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          echo Visit your pr here: http://${{ github.event.pull_request.user.login }}-${{ github.head_ref }}.dickyindra.com
